services:
  nginx-quictls:
    build: nginx-quictls
    expose:
      - "443/tcp"
      - "443/udp"
    volumes:
      - "./nginx-quictls/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx-quictls/docroot:/var/www/html:ro"
      - "./server.crt:/etc/nginx/cert.crt:ro"
      - "./server.key:/etc/nginx/cert.key:ro"
  curl-quictls:
    build: curl-quictls
    depends_on:
      - nginx-quictls
    command: curl -kv --http3 https://nginx-quictls
volumes:
  nginx-quictls-docroot: {}
