services:
  nginx-boringssl:
    build: nginx-boringssl
    expose:
      - "443/tcp"
      - "443/udp"
    volumes:
      - "./nginx-boringssl/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx-boringssl/docroot:/var/www/html:ro"
      - "./server.crt:/etc/nginx/cert.crt:ro"
      - "./server.key:/etc/nginx/cert.key:ro"
  curl-boringssl:
    build: curl-boringssl
    depends_on:
      - nginx-boringssl
    command: curl -sSkv --http3 https://nginx-boringssl
volumes:
  nginx-boringssl-docroot: {}
